import { Component, inject, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators, FormsModule } from '@angular/forms';
import { BlogService } from '../../services/blog.service';
import { Router, ActivatedRoute } from '@angular/router';
import { CommonModule } from '@angular/common';
import { EditorModule } from 'primeng/editor';
import { SelectModule } from 'primeng/select';
import { InputText } from 'primeng/inputtext';
import { Button } from 'primeng/button';

@Component({
  selector: 'app-post-create',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, FormsModule, EditorModule, SelectModule, InputText, Button],
  templateUrl: './post-create.html',
  styleUrl: './post-create.css'
})
export class PostCreate implements OnInit {
  private fb = inject(FormBuilder);
  private blogService = inject(BlogService);
  private router = inject(Router);
  private route = inject(ActivatedRoute);

  users: any[] = [];
  isEditMode = false;
  postSlug: string | null = null;
  submitLabel = 'Publicar Notícia';

  postForm: FormGroup = this.fb.group({
    title: ['', [Validators.required, Validators.minLength(5)]],
    subtitle: ['', Validators.required],
    content: ['', Validators.required],
    author: ['', Validators.required],
    image: [null]
  });

  selectedFile: File | null = null;
  currentImageUrl: string | null = null;

  ngOnInit() {
    this.loadUsers();
    
    const slug = this.route.snapshot.paramMap.get('slug');
    if (slug) {
      this.isEditMode = true;
      this.postSlug = slug;
      this.submitLabel = 'Salvar Alterações';
      this.loadPost(slug);
    }
  }

  loadUsers() {
    this.blogService.getUsers().subscribe(data => {
      this.users = data;
    });
  }

  loadPost(slug: string) {
    this.blogService.getPost(slug).subscribe(post => {
      this.postForm.patchValue({
        title: post.title,
        subtitle: post.subtitle,
        content: post.content,
        author: post.author 
      });
      // Note: Author needs to match the value expected by Select (ID or object). 
      // Assuming backend returns user ID in author field or we need to map it.
      // If backend returns object, we might need to extract ID.
      
      this.currentImageUrl = post.image || null;
    });
  }

  onFileSelected(event: any) {
    const file = event.target.files[0];
    if (file) {
      this.selectedFile = file;
      this.postForm.patchValue({ image: file });
    }
  }

  onSubmit() {
    if (this.postForm.invalid) return;

    const formData = new FormData();
    formData.append('title', this.postForm.get('title')?.value);
    formData.append('subtitle', this.postForm.get('subtitle')?.value);
    formData.append('content', this.postForm.get('content')?.value);
    formData.append('author', this.postForm.get('author')?.value);

    // Slug is generated by backend

    if (this.selectedFile) {
      formData.append('image', this.selectedFile);
    }

    const request$ = this.isEditMode && this.postSlug
      ? this.blogService.updatePost(this.postSlug, formData)
      : this.blogService.createPost(formData);

    request$.subscribe({
      next: (res) => {
        alert(this.isEditMode ? 'Notícia atualizada!' : 'Notícia publicada com sucesso!');
        this.router.navigate(['/admin/posts']);
      },
      error: (err) => {
        console.error('Erro no envio:', err);
        alert('Erro: ' + JSON.stringify(err.error));
      }
    });
  }
}
