services:
  web:
    build: ./backend
    container_name: jornalismo-web
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./backend:/app
      - /app/.venv
    depends_on:
      - db
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=db

  frontend:
    build: ./frontend
    container_name: jornalismo-frontend
    ports:
      - "4200:80"
    restart: always
    depends_on:
      - web


  db:
    image: postgres:16
    restart: always
    container_name: jornalismo-db
    environment:
      POSTGRES_USER: mabelaaaa
      POSTGRES_PASSWORD: Mi150203!@
      POSTGRES_DB: jornalismo
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data


