# Generated by Django 5.0.4 on 2025-12-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtítulo')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('data_publicacao', models.DateTimeField(verbose_name='Data de Publicação')),
                ('local_publicacao', models.CharField(max_length=100, verbose_name='Local de Publicação')),
                ('link_externo', models.URLField(blank=True, null=True, verbose_name='Link Externo')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='artigos/', verbose_name='Imagem')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL Amigável')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
