import { Component, inject, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators, FormsModule } from '@angular/forms';
import { ArtigosService } from '../../services/artigos.service';
import { Router, ActivatedRoute } from '@angular/router';
import { CommonModule } from '@angular/common';
import { EditorModule } from 'primeng/editor';
import { InputText } from 'primeng/inputtext';
import { Button } from 'primeng/button';
import { TextareaModule } from 'primeng/textarea';

import { DatePickerModule } from 'primeng/datepicker';

@Component({
  selector: 'app-artigo-create',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, FormsModule, EditorModule, InputText, Button, TextareaModule, DatePickerModule],
  templateUrl: './artigo-create.html',
  styleUrl: './artigo-create.css'
})
export class ArtigoCreate implements OnInit {
  private fb = inject(FormBuilder);
  private artigosService = inject(ArtigosService);
  private router = inject(Router);
  private route = inject(ActivatedRoute);

  isEditMode = false;
  artigoSlug: string | null = null;
  submitLabel = 'Publicar Artigo';
  
  // Note: 'slug' is auto-generated by backend, so we don't need to send it usually, 
  // but we might need it for public links.

  artigoForm: FormGroup = this.fb.group({
    titulo: ['', [Validators.required, Validators.minLength(5)]],
    subtitulo: [''],
    conteudo: ['', Validators.required],
    data_publicacao: [new Date(), Validators.required],
    local_publicacao: ['', Validators.required],
    link_externo: [''],
    image: [null]
  });

  selectedFile: File | null = null;
  currentImageUrl: string | null = null;

  ngOnInit() {
    const slug = this.route.snapshot.paramMap.get('slug');
    if (slug) {
      this.isEditMode = true;
      this.artigoSlug = slug;
      this.submitLabel = 'Salvar Alterações';
      this.loadArtigo(slug);
    }
  }

  loadArtigo(slug: string) {
    this.artigosService.getArtigo(slug).subscribe(artigo => {
      this.artigoForm.patchValue({
        titulo: artigo.titulo,
        subtitulo: artigo.subtitulo,
        conteudo: artigo.conteudo,
        data_publicacao: new Date(artigo.data_publicacao), // Convert string to Date for Calendar
        local_publicacao: artigo.local_publicacao,
        link_externo: artigo.link_externo
      });
      this.currentImageUrl = artigo.imagem || null;
    });
  }

  onFileSelected(event: any) {
    const file = event.target.files[0];
    if (file) {
      this.selectedFile = file;
      this.artigoForm.patchValue({ image: file });
    }
  }

  onSubmit() {
    if (this.artigoForm.invalid) return;

    const formData = new FormData();
    formData.append('titulo', this.artigoForm.get('titulo')?.value);
    formData.append('subtitulo', this.artigoForm.get('subtitulo')?.value || '');
    formData.append('conteudo', this.artigoForm.get('conteudo')?.value);
    
    // Format date to ISO string or YYYY-MM-DD
    const date = this.artigoForm.get('data_publicacao')?.value;
    if (date instanceof Date) {
        formData.append('data_publicacao', date.toISOString());
    } else {
        formData.append('data_publicacao', date);
    }

    formData.append('local_publicacao', this.artigoForm.get('local_publicacao')?.value);
    formData.append('link_externo', this.artigoForm.get('link_externo')?.value || '');

    if (this.selectedFile) {
      formData.append('imagem', this.selectedFile); // Note: Field is 'imagem' in backend
    }

    const request$ = this.isEditMode && this.artigoSlug
      ? this.artigosService.updateArtigo(this.artigoSlug, formData)
      : this.artigosService.createArtigo(formData);

    request$.subscribe({
      next: (res) => {
        const message = this.isEditMode ? 'Artigo atualizado com sucesso!' : 'Artigo publicado com sucesso!';
        this.router.navigate(['/admin/sucesso'], {
            queryParams: {
                message: message,
                actionLabel: 'Voltar para Artigos',
                actionUrl: '/admin/artigos',
                createLabel: 'Criar novo Artigo',
                createUrl: '/artigos/novo'
            }
        });
      },
      error: (err) => {
        console.error('Erro no envio:', err);
        const errorMessage = err.error?.detail || JSON.stringify(err.error) || 'Não foi possível salvar o artigo.';
        this.router.navigate(['/admin/erro'], {
            queryParams: {
                message: 'Erro ao salvar o artigo.',
                details: errorMessage,
                retryLabel: 'Tentar novamente',
                retryUrl: this.router.url, // Current URL to retry
                backUrl: '/admin/artigos'
            }
        });
      }
    });
  }
}
