import { Component, inject, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators, FormsModule } from '@angular/forms';
import { ArtigosService } from '../../services/artigos.service';
import { Router, ActivatedRoute } from '@angular/router';
import { CommonModule } from '@angular/common';
import { EditorModule } from 'primeng/editor';
import { InputText } from 'primeng/inputtext';
import { Button } from 'primeng/button';
import { TextareaModule } from 'primeng/textarea';

@Component({
  selector: 'app-artigo-create',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, FormsModule, EditorModule, InputText, Button, TextareaModule],
  templateUrl: './artigo-create.html',
  styleUrl: './artigo-create.css'
})
export class ArtigoCreate implements OnInit {
  private fb = inject(FormBuilder);
  private artigosService = inject(ArtigosService);
  private router = inject(Router);
  private route = inject(ActivatedRoute);

  isEditMode = false;
  artigoId: number | null = null;
  submitLabel = 'Publicar Artigo';
  
  // Note: 'slug' is auto-generated by backend, so we don't need to send it usually, 
  // but we might need it for public links.

  artigoForm: FormGroup = this.fb.group({
    titulo: ['', [Validators.required, Validators.minLength(5)]],
    subtitulo: [''],
    conteudo: ['', Validators.required],
    data_publicacao: [new Date(), Validators.required],
    local_publicacao: ['', Validators.required],
    link_externo: [''],
    image: [null]
  });

  selectedFile: File | null = null;
  currentImageUrl: string | null = null;

  ngOnInit() {
    const id = this.route.snapshot.paramMap.get('id');
    if (id) {
      this.isEditMode = true;
      this.artigoId = +id; // Convert to number
      this.submitLabel = 'Salvar Alterações';
      this.loadArtigo(id); // Usually we fetch by ID for admin edit
      // My Service `getArtigo` takes a slug currently in my implementation. 
      // I should check `ArtigosService`. 
      // It says: `getArtigo(slug: string)` and `updateArtigo(id: number...)`.
      // I should probably change `getArtigo` to accept ID or Slug, or simply use ID for edit.
    }
  }

  loadArtigo(idOrSlug: string) {
    // Try to fetch by ID or Slug. 
    // Since my Service `getArtigo` expects a slug currently (based on my memory), 
    // I might need to update the service to support fetching by ID for editing if I don't have the slug available in URL.
    // BUT, the route `/artigos/editar/:id` provides ID.
    // I should update ArtigosService to have `getArtigoById(id: number)` or update `getArtigo` to take `id`.
    // Let's assume for now I will use ID and update service later if needed, or if `getArtigo` url is just `${this.apiUrl}${slug}/` it might work with ID too if backend supports it. 
    // Backend ViewSet supports ID lookup by default.
    
    // I'll assume getArtigo can take the ID as string.
    this.artigosService.getArtigo(idOrSlug).subscribe(artigo => {
      this.artigoForm.patchValue({
        titulo: artigo.titulo,
        subtitulo: artigo.subtitulo,
        conteudo: artigo.conteudo,
        data_publicacao: new Date(artigo.data_publicacao), // Convert string to Date for Calendar
        local_publicacao: artigo.local_publicacao,
        link_externo: artigo.link_externo
      });
      this.currentImageUrl = artigo.imagem || null;
    });
  }

  onFileSelected(event: any) {
    const file = event.target.files[0];
    if (file) {
      this.selectedFile = file;
      this.artigoForm.patchValue({ image: file });
    }
  }

  onSubmit() {
    if (this.artigoForm.invalid) return;

    const formData = new FormData();
    formData.append('titulo', this.artigoForm.get('titulo')?.value);
    formData.append('subtitulo', this.artigoForm.get('subtitulo')?.value || '');
    formData.append('conteudo', this.artigoForm.get('conteudo')?.value);
    
    // Format date to ISO string or YYYY-MM-DD
    const date = this.artigoForm.get('data_publicacao')?.value;
    if (date instanceof Date) {
        formData.append('data_publicacao', date.toISOString());
    } else {
        formData.append('data_publicacao', date);
    }

    formData.append('local_publicacao', this.artigoForm.get('local_publicacao')?.value);
    formData.append('link_externo', this.artigoForm.get('link_externo')?.value || '');

    if (this.selectedFile) {
      formData.append('imagem', this.selectedFile); // Note: Field is 'imagem' in backend
    }

    const request$ = this.isEditMode && this.artigoId
      ? this.artigosService.updateArtigo(this.artigoId, formData)
      : this.artigosService.createArtigo(formData);

    request$.subscribe({
      next: (res) => {
        alert(this.isEditMode ? 'Artigo atualizado!' : 'Artigo publicado com sucesso!');
        this.router.navigate(['/admin/artigos']);
      },
      error: (err) => {
        console.error('Erro no envio:', err);
        alert('Erro: ' + JSON.stringify(err.error));
      }
    });
  }
}
