# Generated by Django 5.0.4 on 2025-12-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_realizacao', models.DateField(verbose_name='Data de Realização')),
                ('tipo', models.CharField(choices=[('academico', 'Acadêmico'), ('pessoal', 'Pessoal')], max_length=20, verbose_name='Tipo de Projeto')),
                ('link_externo', models.URLField(blank=True, null=True, verbose_name='Link do Projeto')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='projetos/', verbose_name='Imagem')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL Amigável')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-data_realizacao'],
            },
        ),
    ]
