# Generated by Django 5.0.4 on 2026-03-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_alter_projeto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='conteudo',
            field=models.TextField(blank=True, null=True, verbose_name='Conteúdo Completo'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(verbose_name='Descrição (Resumo para o card)'),
        ),
    ]
