import { Component, inject } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators, FormsModule } from '@angular/forms';
import { MateriaisService } from '../../services/materiais.service';
import { Router, ActivatedRoute } from '@angular/router';
import { CommonModule } from '@angular/common';
import { SelectModule } from 'primeng/select';
import { InputText } from 'primeng/inputtext';
import { Button } from 'primeng/button';
import { TextareaModule } from 'primeng/textarea';
import { FileUploadModule } from 'primeng/fileupload';
import { InputNumberModule } from 'primeng/inputnumber';

@Component({
  selector: 'app-material-create',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, FormsModule, SelectModule, InputText, Button, TextareaModule, FileUploadModule, InputNumberModule],
  templateUrl: './material-create.html',
  styleUrls: ['./material-create.css']
})
export class MaterialCreate {
  private fb = inject(FormBuilder);
  private materiaisService = inject(MateriaisService);
  private router = inject(Router);
  private route = inject(ActivatedRoute);

  types = [
    { label: 'Gratuito', value: 'gratuito' },
    { label: 'Pago', value: 'pago' }
  ];

  categories = [
    { label: 'Ebook', value: 'ebook' },
    { label: 'Template', value: 'template' },
    { label: 'Curso', value: 'curso' },
    { label: 'Outros', value: 'outros' }
  ];

  selectedImage: File | null = null;
  selectedFile: File | null = null;

  materialForm: FormGroup = this.fb.group({
    name: ['', [Validators.required, Validators.minLength(3)]],
    description: ['', Validators.required],
    category: ['', Validators.required],
    type: ['gratuito', Validators.required],
    price: [null],
    external_link: [''],
    image: [null, Validators.required], // Image is required for cover
    file: [null] // File is optional (can be null if paid/external link)
  });

  onImageSelected(event: any) {
    const file = event.target.files[0];
    if (file) {
      this.selectedImage = file;
      this.materialForm.patchValue({ image: file });
    }
  }

  onFileSelected(event: any) {
    const file = event.target.files[0];
    if (file) {
      this.selectedFile = file;
      this.materialForm.patchValue({ file: file });
    }
  }

  isEditMode = false;
  materialId: number | null = null;

  ngOnInit() {
    this.route.paramMap.subscribe(params => {
      const id = params.get('id');
      if (id) {
        this.isEditMode = true;
        this.materialId = +id;
        this.loadMaterial(this.materialId);
        // Remove required validator for image in edit mode as we might keep existing one
        this.materialForm.get('image')?.clearValidators();
        this.materialForm.get('image')?.updateValueAndValidity();
      }
    });
  }

  loadMaterial(id: number) {
    this.materiaisService.getMaterial(id).subscribe(material => {
      this.materialForm.patchValue({
        name: material.name,
        description: material.description,
        category: material.category,
        type: material.type,
        price: material.price,
        external_link: material.external_link
      });
      // Note: Image and File are not patched directly as inputs are file type
    });
  }

  onSubmit() {
    if (this.materialForm.invalid) return;

    const formData = new FormData();
    formData.append('name', this.materialForm.get('name')?.value);
    formData.append('description', this.materialForm.get('description')?.value);
    formData.append('category', this.materialForm.get('category')?.value);
    formData.append('type', this.materialForm.get('type')?.value);
    
    // Slug is generated by backend

    if (this.materialForm.get('type')?.value === 'pago') {
        const price = this.materialForm.get('price')?.value;
        if (price) formData.append('price', price.toString());
        
        const link = this.materialForm.get('external_link')?.value;
        if (link) formData.append('external_link', link);
    }

    if (this.selectedImage) {
      formData.append('image', this.selectedImage);
    }

    if (this.selectedFile) {
        formData.append('file', this.selectedFile);
    }

    const request$ = this.isEditMode && this.materialId
      ? this.materiaisService.updateMaterial(this.materialId, formData)
      : this.materiaisService.createMaterial(formData);

    request$.subscribe({
      next: (res) => {
        alert(this.isEditMode ? 'Material atualizado com sucesso!' : 'Material criado com sucesso!');
        this.router.navigate(['/admin/materiais']);
      },
      error: (err) => {
        console.error('Erro ao salvar material:', err);
        if (err.status === 0) {
            alert('Erro de conexão: Não foi possível conectar ao servidor. Verifique se o backend está rodando.');
        } else {
            alert(`Erro ${err.status}: ${JSON.stringify(err.error) || err.message}`);
        }
      }
    });
  }
}
