# Generated by Django 5.0.4 on 2025-12-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('file', models.FileField(blank=True, null=True, upload_to='materiais', verbose_name='Arquivo')),
                ('image', models.ImageField(upload_to='materiais', verbose_name='Imagem')),
                ('category', models.CharField(max_length=50, verbose_name='Categoria')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Amigável (ex: sobre-nos)')),
                ('type', models.CharField(choices=[('gratuito', 'Gratuito'), ('pago', 'Pago')], default='gratuito', max_length=50, verbose_name='Tipo (pago ou gratuito)')),
                ('external_link', models.URLField(blank=True, null=True, verbose_name='Link Externo (Para materiais pagos)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
                'ordering': ['-published_date'],
            },
        ),
    ]
