# Generated by Django 5.0.4 on 2025-12-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL Amigável (ex: sobre-nos)'),
        ),
    ]
